sudo: false

jdk:
  - oraclejdk8

addons:
  sonarqube:
    token: $SONARAUTH
  branches:
    - develop
script:
  - sonar-scanner

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
